language: java
sudo: false # faster builds
jdk:
  - openjdk8

after_success:
  # run jacoco test coverage report and upload to codecov.io
  - mvn org.jacoco:jacoco-maven-plugin:report
  - bash <(curl -s https://codecov.io/bash)
